In [2]:
import numpy as np

def gram_schmidt_qr(A):
    m, n = A.shape
    Q = np.zeros((m, n))
    R = np.zeros((n, n))

    for j in range(n):
        v = A[:, j]
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], A[:, j])
            v = v - R[i, j] * Q[:, i]
        R[j, j] = np.linalg.norm(v)
        Q[:, j] = v / R[j, j]

    return Q, R


A = np.array([[2.0, 1.0, -1.0], [1.0, 1.0, 0.0], [ 0.0, 2.0, 1.0]])
Q, R = gram_schmidt_qr(A)

print("Q:")
print(Q)
print("R:")
print(R)
print("A:")
print(np.dot(Q,R))



Q:
[[ 0.89442719 -0.09759001 -0.43643578]
 [ 0.4472136   0.19518001  0.87287156]
 [ 0.          0.97590007 -0.21821789]]
R:
[[ 2.23606798  1.34164079 -0.89442719]
 [ 0.          2.04939015  1.07349008]
 [ 0.          0.          0.21821789]]
A:
[[ 2.00000000e+00  1.00000000e+00 -1.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00  1.57825627e-18]
 [ 0.00000000e+00  2.00000000e+00  1.00000000e+00]]


In [3]:
#B
def HilbertMatrix(n):
  H = [[0 for x in range(n)] for y in range(n)]
  for i in range(n):
    for j in range(n):
      H[i][j] = 1 / ( i + j + 1 )
  return H
n = 100
print(HilbertMatrix(n))

[[1.0, 0.5, 0.3333333333333333, 0.25, 0.2, 0.16666666666666666, 0.14285714285714285, 0.125, 0.1111111111111111, 0.1, 0.09090909090909091, 0.08333333333333333, 0.07692307692307693, 0.07142857142857142, 0.06666666666666667, 0.0625, 0.058823529411764705, 0.05555555555555555, 0.05263157894736842, 0.05, 0.047619047619047616, 0.045454545454545456, 0.043478260869565216, 0.041666666666666664, 0.04, 0.038461538461538464, 0.037037037037037035, 0.03571428571428571, 0.034482758620689655, 0.03333333333333333, 0.03225806451612903, 0.03125, 0.030303030303030304, 0.029411764705882353, 0.02857142857142857, 0.027777777777777776, 0.02702702702702703, 0.02631578947368421, 0.02564102564102564, 0.025, 0.024390243902439025, 0.023809523809523808, 0.023255813953488372, 0.022727272727272728, 0.022222222222222223, 0.021739130434782608, 0.02127659574468085, 0.020833333333333332, 0.02040816326530612, 0.02, 0.0196078431372549, 0.019230769230769232, 0.018867924528301886, 0.018518518518518517, 0.01818181818181818, 0.

In [4]:
#C

n = 12
A = HilbertMatrix(n)
Q, R = gram_schmidt_qr(np.array(A))

print("Q:")
print(Q)
print("R:")
print(R)
print("A:")
print(np.dot(Q,R))

Q:
[[ 0.79936673 -0.55256396  0.22311461 -0.07368422  0.02112684 -0.00534537
   0.00123508  0.00116007 -0.00118153 -0.00118591 -0.00118768 -0.00118862]
 [ 0.39968337  0.23629494 -0.64382256  0.52450162 -0.28206801  0.11658161
  -0.04000216 -0.03816871  0.03873932  0.03886663  0.03892209  0.03895318]
 [ 0.26645558  0.32838894 -0.30241651 -0.28279077  0.57629276 -0.48126215
   0.27215267  0.26245717 -0.26593789 -0.26681733 -0.26723599 -0.26748537]
 [ 0.19984168  0.32317824 -0.05617549 -0.42067266  0.14751788  0.37210208
  -0.55236729 -0.53501933  0.54293202  0.54526722  0.5464806   0.54724165]
 [ 0.15987335  0.29954875  0.08933358 -0.32684696 -0.21321448  0.37965813
   0.08452928  0.07466434 -0.08114079 -0.08337595 -0.08461663 -0.0854204 ]
 [ 0.13322779  0.27403238  0.17368555 -0.1806813  -0.34694639  0.0575084
   0.40295428  0.3994877  -0.40166101 -0.40240077 -0.40282098 -0.40310125]
 [ 0.11419525  0.25057603  0.222329   -0.0401903  -0.32055268 -0.22115418
   0.24117048  0.24827166 -0.2

D
<div dir=rtl>
به ازای مقادیر تا مقیاس 10 به توان 3  برای n  الگوریتم به خوبی کار میکند و زیر یک دقیقه جواب می دهد.
